### ISSUE TITLE
Naming: pick one of “run” or "execute”.

### ISSUE THREAD

**Issue by k0001** [karamaan/karamaan-opaleye#23]
The use of the words “run” and “execute” in names like `runQuery` and `executeInsertDef` could be simplified by always using either “run” or “execute”.

**Comment by tomjaguarpaw** [comment]
Yes, this is an inconsistency.

**Comment by tomjaguarpaw** [comment]
I guess I'll just go for run because it's shorter!

**Comment by tomjaguarpaw** [comment]
Closed by https://github.com/karamaan/karamaan-opaleye/commit/5cb38929f8c88f77019e151ca267a86707526d7d
