### ISSUE TITLE
Need a generic way to make `Foo -> Expr WireFoo`

### ISSUE THREAD

**Issue by tomjaguarpaw** [karamaan/karamaan-opaleye#4]
It would be handy to have a function like `Foo -> Expr WireFoo` automatically generated, which would treat the values in the fields of the given `Foo` as constants.

`ExprArr.constant` is a partial implementation of this. It can only output one `Wire` so a generalization is needed, which will probably be done, as usual, via `ProductProfunctor` and the `Default` typeclass.

**Comment by tomjaguarpaw** [comment]
Solved by

https://github.com/karamaan/karamaan-opaleye/blob/dev/Karamaan/Opaleye/MakeExpr.hs

**Comment by bergmark** [comment]
Cool!

**Comment by dbp** [comment]
This is really great!
