### ISSUE TITLE
ORDER BY and LIMIT not supported

### ISSUE THREAD

**Issue by tomjaguarpaw** [karamaan/karamaan-opaleye#8]
ORDER BY and LIMIT are not supported.

**Comment by tomjaguarpaw** [comment]
It's unclear to me what the best thing to do here.  ORDER BY and LIMIT have an awkward relationship with the relational model.  However, in the interests of pragmatism it's probably best just to add these to Opaleye and be done with it.

**Comment by tomjaguarpaw** [comment]
An interested party can add these.  It would be a good starter project for getting into Opaleye development.

https://github.com/karamaan/karamaan-opaleye/blob/dev/TODO.md

**Comment by bergmark** [comment]
We need this so I'll try it out.

**Comment by tomjaguarpaw** [comment]
Give me a shout if you need any help.  If necessary I can be available on IRC to help you through it.

**Comment by tomjaguarpaw** [comment]
@hesselink implemented these.
