### ISSUE TITLE
Add UTCTime support

### ISSUE THREAD

**Issue by tomjaguarpaw** [karamaan/karamaan-opaleye#9]
Add support for working with `UTCTime`.

**Comment by tomjaguarpaw** [comment]
We should now add this to ShowConstant.

**Comment by bergmark** [comment]
I have code for this! Ill send a PR

**Comment by bergmark** [comment]
Actually, I just had a `Database.Haskell.Query.ShowConstant` orphan instance:

``` haskell
instance ShowConstant UTCTime where
  showConstant = StringLit . formatTime defaultTimeLocale format
    where
      format :: String
      format = "%Y-%m-%dT%H:%M:%SZ"
```

which means i can do `constant someUTC`.

The Opaleye ShowConstant instance, should that be

``` haskell
instance ShowConstant UTCTime UTCTime where
  showConstant = E.constantLit . PQ.StringLit . formatTime defaultTimeLocale format
    where
      format = "%Y-%m-%dT%H:%M:%SZ"
```

? And how do I use it?

**Comment by tomjaguarpaw** [comment]
You can "use" it with the functions in `MakeExpr`.  For example `MakeExpr.makeExpr :: (UTCTime, String, Double) -> Expr (Wire UTCTime, Wire String, Wire Double)`.

(I'm not certain if `StringLit` is the best thing to use but HaskellDB doesn't have a spec so if it works I guess it doesn't matter for now.  The alternative would be to use `OtherLit` and put it in single quotes manually.)

**Comment by tomjaguarpaw** [comment]
Adam added this

https://github.com/karamaan/karamaan-opaleye/commit/de8a4bc0d1eb17eba553426600f85a7720782d5b
